-- Setup script for the Apothecaries database and wizard_shop_developer role (dbt workshop)

----------------------------------------------------------------------
-- 1. CREATE DATABASE
----------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS APOTHECARIES;

----------------------------------------------------------------------
-- 2. CREATE SCHEMAS
----------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS APOTHECARIES.RAW;
CREATE SCHEMA IF NOT EXISTS APOTHECARIES.STAGING;
CREATE SCHEMA IF NOT EXISTS APOTHECARIES.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS APOTHECARIES.MARTS;

----------------------------------------------------------------------
-- 3. CREATE ROLE
----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS WIZARD_SHOP_DEVELOPER;

-- Grant the role to the current user (adjust as needed for workshop participants)
GRANT ROLE WIZARD_SHOP_DEVELOPER TO ROLE ACCOUNTADMIN;

----------------------------------------------------------------------
-- 4. WAREHOUSE ACCESS
----------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE TRANSFORMING TO ROLE WIZARD_SHOP_DEVELOPER;

----------------------------------------------------------------------
-- 5. DATABASE & SCHEMA GRANTS
----------------------------------------------------------------------
GRANT ALL PRIVILEGES ON DATABASE APOTHECARIES TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT CREATE SCHEMA ON DATABASE APOTHECARIES TO ROLE WIZARD_SHOP_DEVELOPER;

GRANT ALL PRIVILEGES ON SCHEMA APOTHECARIES.RAW TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON SCHEMA APOTHECARIES.STAGING TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON SCHEMA APOTHECARIES.INTERMEDIATE TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON SCHEMA APOTHECARIES.MARTS TO ROLE WIZARD_SHOP_DEVELOPER;

-- Future schemas created in this database
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE APOTHECARIES TO ROLE WIZARD_SHOP_DEVELOPER;

----------------------------------------------------------------------
-- 6. TABLE GRANTS (existing + future)
----------------------------------------------------------------------
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APOTHECARIES.RAW TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APOTHECARIES.STAGING TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APOTHECARIES.INTERMEDIATE TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APOTHECARIES.MARTS TO ROLE WIZARD_SHOP_DEVELOPER;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APOTHECARIES.RAW TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APOTHECARIES.STAGING TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APOTHECARIES.INTERMEDIATE TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APOTHECARIES.MARTS TO ROLE WIZARD_SHOP_DEVELOPER;

----------------------------------------------------------------------
-- 7. VIEW GRANTS (existing + future)
----------------------------------------------------------------------
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA APOTHECARIES.RAW TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA APOTHECARIES.STAGING TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA APOTHECARIES.INTERMEDIATE TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA APOTHECARIES.MARTS TO ROLE WIZARD_SHOP_DEVELOPER;

GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA APOTHECARIES.RAW TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA APOTHECARIES.STAGING TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA APOTHECARIES.INTERMEDIATE TO ROLE WIZARD_SHOP_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA APOTHECARIES.MARTS TO ROLE WIZARD_SHOP_DEVELOPER;

----------------------------------------------------------------------
-- 8. GRANT ROLE TO USER
----------------------------------------------------------------------

GRANT ROLE WIZARD_SHOP_DEVELOPER TO USER <participant>;